apiVersion: v1
kind: Service
metadata:
  labels:
    app: push-notifications
    environment: Development
  name: push-notifications
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: push-notifications
  sessionAffinity: None
  type: ClusterIP
